import img from '../../assets/Our Team/Image.png';
import img1 from '../../assets/Our Team/Image (1).png';
import img2 from '../../assets/Our Team/Image (2).png';
import img3 from '../../assets/Our Team/Image(3).png';
class Employee{
    constructor (id,profilePicture,name,name_ar,title,title_ar,section,email,facebook,linkedin,github,behance){
        this.id= id,
        this.profilePicture=profilePicture,
        this.name=name,
        this.name_ar=name_ar,
        this.title=title,
        this.title_ar=title_ar,
        this.section=section,
        this.email=email,
        this.facebook=facebook,
        this.linkedin=linkedin,
        this.github=github,
        this.behance=behance
    }
}
export const team=[
    new Employee(1,img,"Wade Warren","م","Founder","مؤسس","managers","ee","ff","ll","gg","bb"),
    new Employee(2,img1,"Maya Davies","م","Art Director (Employee)","مدير فني ( موظف )","others","ee","ff","ll","gg","bb"),
    new Employee(3,img2,"Max Mitchell","م","Brand Strategist","استراتيجي العلامة التجارية","non-technical","ee","ff","","gg","bb"),
    new Employee(4,img3,"Kara Perry","م","Graphic Designer","مصمم جرافيك","designers","ee","ff","","","bb"),
    new Employee(5,img,"Wade Warren","م","Founder","مؤسس","managers","ee","ff","","",""),
    new Employee(6,img1,"Maya Davies","م","Art Director (Employee)","مدير فني ( موظف )","others","ee","ff","ll","gg","bb"),
    new Employee(7,img2,"Max Mitchell","م","Brand Strategist","استراتيجي العلامة التجارية","non-technical","ee","ff","ll","gg",""),
    new Employee(8,img3,"Kara Perry","م","Graphic Designer","مصمم جرافيك","designers","ee","ff","ll","","bb"),
    new Employee(9,img,"Wade Warren","م","Founder","مؤسس","managers","ee","ff","ll","gg","bb"),
    new Employee(10,img1,"Maya Davies","م","Art Director (Employee)","مدير فني ( موظف )","others","ee","ff","ll","gg","bb"),
    new Employee(11,img2,"Max Mitchell","م","Brand Strategist","استراتيجي العلامة التجارية","non-technical","ee","ff","","gg","bb"),
    new Employee(12,img3,"Kara Perry","م","Graphic Designer","مصمم جرافيك","designers","ee","ff","","","bb"),
    new Employee(13,img,"Wade Warren","م","Founder","مؤسس","managers","ee","ff","","",""),
    new Employee(14,img1,"Maya Davies","م","Art Director (Employee)","مدير فني ( موظف )","others","ee","ff","ll","gg","bb"),
    new Employee(15,img2,"Max Mitchell","م","Brand Strategist","استراتيجي العلامة التجارية","non-technical","ee","ff","ll","gg",""),
    new Employee(16,img3,"Kara Perry","م","Graphic Designer","مصمم جرافيك","designers","ee","ff","ll","","bb"),
    new Employee(17,img,"Wade Warren","م","Founder","مؤسس","managers","ee","ff","ll","gg","bb"),
    new Employee(18,img1,"Maya Davies","م","Art Director (Employee)","مدير فني ( موظف )","others","ee","ff","ll","gg","bb"),
    new Employee(19,img2,"Max Mitchell","م","Brand Strategist","استراتيجي العلامة التجارية","non-technical","ee","ff","","gg","bb"),
    new Employee(20,img3,"Kara Perry","م","Graphic Designer","مصمم جرافيك","designers","ee","ff","","","bb"),
    new Employee(21,img,"Wade Warren","م","Founder","مؤسس","managers","ee","ff","","",""),
    new Employee(22,img1,"Maya Davies","م","Art Director (Employee)","مدير فني ( موظف )","others","ee","ff","ll","gg","bb"),
    new Employee(23,img2,"Max Mitchell","م","Brand Strategist","استراتيجي العلامة التجارية","non-technical","ee","ff","ll","gg",""),
    new Employee(24,img3,"Kara Perry","م","Graphic Designer","مصمم جرافيك","designers","ee","ff","ll","","bb"),
    new Employee(25,img,"Wade Warren","م","Founder","مؤسس","managers","ee","ff","ll","gg","bb"),
    new Employee(26,img1,"Maya Davies","م","Art Director (Employee)","مدير فني ( موظف )","others","ee","ff","ll","gg","bb"),
    new Employee(27,img2,"Max Mitchell","م","Brand Strategist","استراتيجي العلامة التجارية","non-technical","ee","ff","","gg","bb"),
    new Employee(28,img3,"Kara Perry","م","Graphic Designer","مصمم جرافيك","designers","ee","ff","","","bb"),
    new Employee(29,img,"Wade Warren","م","Founder","مؤسس","managers","ee","ff","","",""),
    new Employee(30,img1,"Maya Davies","م","Art Director (Employee)","مدير فني ( موظف )","others","ee","ff","ll","gg","bb"),
    new Employee(31,img2,"Max Mitchell","م","Brand Strategist","استراتيجي العلامة التجارية","non-technical","ee","ff","ll","gg",""),
    new Employee(32,img3,"Kara Perry","م","Graphic Designer","مصمم جرافيك","designers","ee","ff","ll","","bb"),
    new Employee(33,img,"Wade Warren","م","Founder","مؤسس","managers","ee","ff","ll","gg","bb"),
    new Employee(34,img1,"Maya Davies","م","Art Director (Employee)","مدير فني ( موظف )","others","ee","ff","ll","gg","bb"),
    new Employee(35,img2,"Max Mitchell","م","Brand Strategist","استراتيجي العلامة التجارية","non-technical","ee","ff","","gg","bb"),
    new Employee(36,img3,"Kara Perry","م","Graphic Designer","مصمم جرافيك","designers","ee","ff","","","bb"),
    new Employee(37,img,"Wade Warren","م","Founder","مؤسس","managers","ee","ff","","",""),
    new Employee(38,img1,"Maya Davies","م","Art Director (Employee)","مدير فني ( موظف )","others","ee","ff","ll","gg","bb"),
    new Employee(39,img2,"Max Mitchell","م","Brand Strategist","استراتيجي العلامة التجارية","non-technical","ee","ff","ll","gg",""),
    new Employee(40,img3,"Kara Perry","م","Graphic Designer","مصمم جرافيك","designers","ee","ff","ll","","bb"),
    new Employee(41,img,"Wade Warren","م","Founder","مؤسس","managers","ee","ff","ll","gg","bb"),
    new Employee(42,img1,"Maya Davies","م","Art Director (Employee)","مدير فني ( موظف )","others","ee","ff","ll","gg","bb"),
    new Employee(43,img2,"Max Mitchell","م","Brand Strategist","استراتيجي العلامة التجارية","non-technical","ee","ff","","gg","bb"),
];
